on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  actions: write

jobs:
  codacy-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Codacy configuration
        run: |
          echo "tools:
            trivy:
              enabled: true
              patterns:
                - vuln
                - misconfig" > .codacy.yaml

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Codacy CLI
        run: |
          curl -Ls https://github.com/codacy/codacy-analysis-cli/releases/latest/download/codacy-analysis-cli-linux -o codacy-analysis-cli
          chmod +x codacy-analysis-cli
          sudo mv codacy-analysis-cli /usr/local/bin/

      - name: Run Codacy Analysis CLI
        run: |
          codacy-analysis-cli analyze --tool trivy --output-format text

      - name: Display Codacy Results
        run: echo "Codacy analysis completed. Check the logs above for details."